version: '3.7'

services:
#  http-user:
#    image: barbar:latest
#    ports:
#      - "3000:3000"
#    expose:
#      - "3000"
#    command: "http-user"
#    depends_on:
#      redis:
#        condition: service_started
#      mongo:
#        condition: service_started
#    restart: always
#    links:
#      - mongo
#      - redis
#    volumes:
#      - barbar:/var/go
#    networks:
#      - barbar
#
#  http-auth:
#    image: barbar:latest
#    ports:
#      - "3001:3001"
#    expose:
#      - "3001"
#    command: "http-auth"
#    depends_on:
#      redis:
#        condition: service_started
#      mongo:
#        condition: service_started
#      grpc-user:
#        condition: service_started
#    restart: always
#    links:
#      - mongo
#      - redis
#      - grpc-user
#    volumes:
#      - barbar:/var/go
#    networks:
#      - barbar
#  grpc-user:
#    image: barbar:latest
#    ports:
#      - "3002:3002"
#    expose:
#      - "3002"
#    command: "grpc-user"
#    depends_on:
#      redis:
#        condition: service_started
#      mongo:
#        condition: service_started
#    restart: always
#    links:
#      - mongo
#      - redis
#    volumes:
#      - barbar:/var/go
#    networks:
#      - barbar
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - barbar
  redis:
    image: 'bitnami/redis:latest'
    ports:
      - '6000:6379'
    expose:
      - '6000'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=akupushinglagi
    volumes:
      - cache:/var/lib/redis
    networks:
      - barbar
volumes:
  mongodb_data_container:
  cache:
  barbar:

networks:
  barbar:
    driver: bridge
